[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; This ensures the compiled binary is always in a predictable spot for Wokwi
build_type = debug

;    ABOUT THE COMPATIBLE PROBLEM BETWEEN VSCode AND WOKWI ONLINE:

;    Recently, the company behind the ESP32 (Espressif) and the team behind PlatformIO had a falling out over business agreements. 
;    Because of this, PlatformIO officially refuses to support Arduino Core 3.x. 
;    Even if you download the absolute newest official PlatformIO update, they intentionally freeze the Arduino framework at version 2.0.17.
;    Meanwhile, Wokwi Online and the standard Arduino IDE have happily moved on to version 3.x.
